name: 🐞 ODS – Error o mejora técnica
title: "🐞 ODS – Error o mejora técnica: [Nombre de tu requerimiento]"
description: "Reportá un error o sugerí una mejora técnica en el sistema de diseño Obelisco."
labels: ["bug", "technical improvement"]
body:
  - type: markdown
    attributes:
      value: "## Describí el error o la mejora técnica"
  
  - type: textarea
    id: descripcion
    attributes:
      label: "Descripción"
      description: "Escribí en pocas palabras, de forma clara y concreta, cuál es el error o la mejora técnica encontrada."
      placeholder: "Ejemplo: El componente de botones no responde al cambio de tamaño en dispositivos móviles."
    validations:
      required: true

  - type: markdown
    attributes:
      value: "## ¿Cómo reproducirlo?"
  
  - type: textarea
    id: reproducir
    attributes:
      label: "Pasos para reproducir"
      description: "Identificá los pasos para reproducir el error o el punto de dolor."
      placeholder: "1. Ir a '...'\n2. Hacer click en '...'\n3. Navegar hasta '...'\n4. Error"
    validations:
      required: true

  - type: markdown
    attributes:
      value: "## Comportamiento esperado"
  
  - type: textarea
    id: comportamiento_esperado
    attributes:
      label: "Descripción"
      description: "Describí el comportamiento esperado de forma clara y concisa."
      placeholder: "Ejemplo: El botón debe ajustarse correctamente al tamaño del contenedor en todas las resoluciones."
    validations:
      required: true

  - type: markdown
    attributes:
      value: "## Código relacionado"
  
  - type: textarea
    id: codigo_relacionado
    attributes:
      label: "Fragmento de código"
      description: "Incluí imágenes o extractos del código relacionados al error o punto de dolor."
      placeholder: "Adjuntá el código relevante aquí."
    validations:
      required: false

  - type: markdown
    attributes:
      value: "## Capturas de pantalla"
  
  - type: textarea
    id: capturas
    attributes:
      label: "Capturas de pantalla"
      description: "Tomá capturas de pantalla del error o punto de dolor en el entorno en el que se encuentre (producción o desarrollo)."
      placeholder: "Adjuntá imágenes relevantes aquí."
    validations:
      required: false

  - type: markdown
    attributes:
      value: "## Versión de Obelisco"
  
  - type: dropdown
    id: version_obelisco
    attributes:
      label: "Versión en uso"
      description: "Seleccioná la versión del sistema de diseño que utilices."
      options:
        - "Obelisco v2"
        - "Obelisco v1 (Sin soporte)"
    validations:
      required: true

  - type: markdown
    attributes:
      value: "## Configuración del sistema/Tecnología en uso"
  
  - type: input
    id: configuracion_sistema
    attributes:
      label: "Información del sistema"
      description: "Identificá el dispositivo, sistema operativo, navegador y versión del navegador relacionado al issue."
      placeholder: "Ejemplo: Desktop / Windows 11 / Chrome 22"
    validations:
      required: true

  - type: markdown
    attributes:
      value: "## Información adicional"
  
  - type: textarea
    id: info_adicional
    attributes:
      label: "Detalles adicionales"
      description: "Sumá cualquier información adicional que consideres necesaria para entender el error o punto de dolor."
    validations:
      required: false

  - type: markdown
    attributes:
      value: "## ¿Tenés algo adelantado o querés contribuir a la solución?"
  
  - type: checkboxes
    id: contribucion
    attributes:
      label: "¿Querés contribuir a la solución?"
      description: "Si realizaste pruebas o exploraciones, o querés contribuir con la solución, seleccioná la opción."
      options:
        - label: "Sí, quiero y contribuiré a la solución del problema."
          required: false
